### ISSUE TITLE
issue in latest ionic 3.5.0

### ISSUE THREAD

**Issue by donernacio** [zyra/ionic2-super-tabs#111]
![screen shot 2017-07-12 at 7 57 57 pm](https://user-images.githubusercontent.com/6898593/28116646-83032202-673c-11e7-844e-6193574960bd.png)

Runtime Error
Uncaught (in promise): Error: Type TalksPage is part of the declarations of 2 modules: AppModule and TalksPageModule! Please consider moving TalksPage to a higher module that imports AppModule and TalksPageModule. You can also create a new NgModule that exports and includes TalksPage then import that NgModule in AppModule and TalksPageModule. Error: Type TalksPage is part of the declarations of 2 modules: AppModule and TalksPageModule! Please consider moving TalksPage to a higher module that imports AppModule and TalksPageModule. You can also create a new NgModule that exports and includes TalksPage then import that NgModule in AppModule and TalksPageModule. at syntaxError

**Comment by ihadeed** [comment]
Doesn't look like an issue with this module. The error message is saying that the component `TalksPage` is included in two modules. It's probably because you're using lazy loading and you also have the `TalksPage` component defined the app's main module. Check `src/app/app.module.ts` and remove `TalksPage` from there.
