### ISSUE TITLE
slideTo method cause ionic to push a page on navstack

### ISSUE THREAD

**Issue by aavelyn** [zyra/ionic2-super-tabs#122]
Hi, first of all great job!

I'm using your lib only to enable sliding between pages, hence I have to rely on the swipeTo method.
When I call it, passing a page index, it does slide to the said page, but somehow also pushes that same page onto the ionic nav stack. Any ideas why?

Cheers

**Comment by ihadeed** [comment]
Hey there,

I just tried to reproduce this but it seems to work fine.

This is my code:
```ts
@ViewChild(SuperTabs) superTabs: SuperTabs;

ngAfterViewInit() {
  setTimeout(() => {
    this.superTabs.slideTo(4);
  }, 3000);
}
```

**Comment by BenHen75** [comment]
Hey! First of all, thank you for the awesome work you do to ionic community!

I think this bug is quite similar:

In your ionic2-super-tabs-example, on app.component, if instead of setRoot to open a new page we use push, the ionic nav stack look wrong, it add nav to url instead of replacing it: 

http://localhost:8101/#/home/all/nav/n6/page2/nav/n143/page1/nav/n156/page1/nav/n169/page1  

And if in menu we use this.superTabsCtrl.slideTo(1, 'page1') it doesn't work.

Thanks

**Comment by ihadeed** [comment]
`push` adds a page to stack instead of replacing it ... so URL will end up with more pages instead of replacing the previous ones.
