### ISSUE TITLE
rootNavCtrl is undefined

### ISSUE THREAD

**Issue by longdw** [zyra/ionic2-super-tabs#126]
there has three tabs, in the first and second tab, `this.rootNavCtrl = navParams.get('rootNavCtrl');` this can work normally, but in the third tab` this.rootNavCtrl`is undefined.

```
<super-tabs *ngIf="menus" [config]="{ sideMenu: 'left' }" 
        toolbarColor="primary" toolbarBackground="slideTabColor" 
        indicatorColor="primary" (tabSelect)="onTabSelect($event)">
        <super-tab *ngFor="let item of menus" [root]="pageContent" [title]="item.name" [rootParams]="getParams(item)"></super-tab>
</super-tabs>
```

in `pageContent`, i got rootNavCtrl like this:
```
constructor(private params: NavParams) {
        super();
        this.rootNavCtrl = params.get('rootNavCtrl');
        console.log(' nav-->' + this.rootNavCtrl);
    }
```

**Comment by ihadeed** [comment]
Seems to be working fine in the example project. Can you verify if it still is an issue? and if it is somehow caused by your extended class?

**Comment by longdw** [comment]
@ihadeed  yes, the question is still exist. I found the reason caused this question. When I delete  `[rootParams]="getParams(item)"`, it works fine.The `getParams(...)` method is:
```
getParams(item) {
        let params = {
            title: 'test'
        };
        return params;
    }
```
you can see this [github example](https://github.com/longdw/TestSuperTab), glad to see your response, thank you very much.

**Comment by ihadeed** [comment]
So sorry for the late response @longdw 

Seems like the issue is that you're using `getParams` function. When you use a function, Angular will keep calling that function to make sure the value didn't change. So it ends up updating the `rootParams` for that tab multiple times, and `super-tabs` only sets the value once. I just fixed that to make sure we always have `rootNavParams` :)
