### ISSUE TITLE
Performance Issue on Android

### ISSUE THREAD

**Issue by sudhanshu-pantelwar** [zyra/ionic2-super-tabs#147]
I am getting some performance issues while using it in device.
While sliding the page freezes for a moment before getting to the next page but when I click on the tab, it doesn't.
What could be the cause for this?

Here is a link explaining the issue:
https://drive.google.com/open?id=0B6mManAqlfpSRWNZanpwbTEzOTg

I am not using any lifecycle events in my code.

Ionic Info:
cli packages: (/home/jash/Desktop/ionicSud/insaniyat/node_modules)

    @ionic/cli-utils  : 1.9.2
    ionic (Ionic CLI) : 3.9.2

global packages:

    Cordova CLI : 7.0.1 

local packages:

    @ionic/app-scripts : 2.1.3
    Cordova Platforms  : android 6.2.3
    Ionic Framework    : ionic-angular 3.6.0

System:

    Android SDK Tools : 25.2.5
    Node              : v6.11.2
    npm               : 3.10.10 
    OS                : Linux 4.4

Thanks.

**Comment by ihadeed** [comment]
Can't see the issue..

**Comment by lincolnthree** [comment]
This is due to the way that the transitioning/animation between slides is performed. The swipe gesture results in a transition that does not exactly match the velocity with which the user has moved their finger. The cubic-bezier() function is "close", but not an exact replacement for handling velocity via the calculated time-delta of the distance the gesture covered over the time it occurred. Something like this:

```
    setProgressEnd (shouldComplete: boolean, currentStepValue: number, velocity: number, done: Function) {
        const ani = this.ani;
        ani.onFinish(() => {
            done();
        }, true);

        const factor = 1 - Math.min(Math.abs(velocity) / 4, 0.7);
        const dur = ani.getDuration() * (factor * 1.3);
        // const dur = (ani.getDuration() > 0) ? Math.max(100, ani.getDuration() * factor) : 0;
        // const dur = 100;

        ani.progressEnd(shouldComplete, currentStepValue, dur);
    }
```

This of course complicates the animation, but you can see how this is done in the Ionic Swipe-Back gestures: 

https://github.com/ionic-team/ionic/blob/master/core/src/utils/gesture/swipe-back.ts

**Comment by svzi** [comment]
@lincolnthree Does that mean we have to live with that kind of lag, or is there anything we could do about?

This just doesn't feel smooth on a real device. Feels sluggish.
