### ISSUE TITLE
Swiping within swipe.

### ISSUE THREAD

**Issue by Arieru** [zyra/ionic2-super-tabs#194]
Does the swipe within tabs affects the function when having ion-sliding-list's swiping gesture? Does it overlap? or does it function well?

**Comment by marcd123** [comment]
@Arieru I'm currently trying to use a map on a super tab that you can swipe around to navigate the map. I have swiping tabs disabled on that page, however there are still some issues. Swiping horizontally still registers as a super tab swipe and not a map swipe even though swiping tabs is disabled. You also still have the padding on the sides that's meant for a sidebar menu, which should be disabled as well.

You can change the padding on the sides to accommodate for a menu and change the minimum distance/angle you need to swipe in order to trigger the super tab sliding as opposed to an ion-item-sliding.

**Comment by ihadeed** [comment]
You can play around with the config here https://github.com/zyra/ionic2-super-tabs#config

In general this doesn't sound like a good user experience. Too many things that can be swiped in the same place.
