### ISSUE TITLE
can you do this with ion-tabs instead of using super tabs the exact same functionality?

### ISSUE THREAD

**Issue by rakeshtinku** [zyra/ionic2-super-tabs#239]

**Comment by ihadeed** [comment]
I don't know, and at this point there's no point in investigating that. 

This module was based of `ion-slides` before, which wasn't a good idea because of performance issues. Yes, I can probably hack `ion-tabs` and other components to get this result, but I'm not sure how the performance would be.. not a big fan of hacky code.

This is now a custom module that consists of custom built components. Allows maximum control + customization, with minimal changes that I have to make when the Ionic team updates their framework code. 

Super tabs still extends/implements the Ionic NavControllerBase, so it still behaves like a regular Nav (or tab).
