### ISSUE TITLE
Active Tab Indicator has the wrong size

### ISSUE THREAD

**Issue by diegozuber** [zyra/ionic2-super-tabs#264]
I use a tab bar only with Ionicons. The Indicator under the tabs don't initialize with the right size. Did someone had already such a problem?

One special thing to add. It DO NOT work on Chrome for development (ionic serve) and it also not work with android, but it works fine on ios.

![bildschirmfoto 2018-02-13 um 10 04 02 am](https://user-images.githubusercontent.com/21689209/36141513-41ea44f4-10a5-11e8-80e1-b6ccab2a02aa.png)
![bildschirmfoto 2018-02-13 um 10 03 53 am](https://user-images.githubusercontent.com/21689209/36141514-4216b82c-10a5-11e8-89c8-03f141d26c64.png)

**Comment by DeniE46** [comment]
@diegozuber I have the same problem both on Chrome and Android device, haven't tested on Ios yet. A few issues back, there seems to be a fix for this, although I couldn't get it running, all I got was "Cannot read property indexSegmentButtonWidths of undefined". Here #69 this problem is discussed as well, and here #121 is the suggested sollution that didn't work for me.
I have to point out however that I have this bug recreated by going to landscape mode, hide the Toolbar, rotate the device back to portrait mode and set the Toolbar visible again.

**Comment by ihadeed** [comment]
What version of this module & Ionic are you using?
Last time I checked this issue was resolved.

**Comment by Zakharen** [comment]
same problem

**Comment by Zakharen** [comment]
Credits to @andryuha49
div.tab-buttons {
    display: table !important;
    super-tab-button {
      display: table-cell !important;
    }
  }

fixed an issue

**Comment by DeniE46** [comment]
@Zakharen, could you provide some more details regarding the implementation of this class? Where do you apply it and so on. Thanks!

**Comment by Zakharen** [comment]
@DeniE46 , sorry for such late response, your 

> <super-tabs>...</super-tabs>

 has an inner element <div> with class name "tab-buttons", you could find it with chrome dev tools HTML inspector, that's why it's just enough to add style code snippet from my prev comment to your ionic page style.

**Comment by DeniE46** [comment]
@Zakharen , thanks, will test ASAP.
