### ISSUE TITLE
Is there a way my tab component can be identified when it's selected.

### ISSUE THREAD

**Issue by grimace** [zyra/ionic2-super-tabs#42]

**Comment by ihadeed** [comment]
So you're trying to know what component (page) is active inside the tab that was selected?

**Comment by grimace** [comment]
just want to know if a particular super-tab component can be notified when it is tabbed to.  
not:
onNgInit or ngAfterViewInit, because they hit just one time.  Something like,  'tabbedAwayFromMe' 'tabbedToMe'.

**Comment by karlvd** [comment]
@grimace I have opened an issue for this already
see #37 

If you need a temporary solution you could
1. use the tabSelect event in the component holding the tabs, use this event to publish an event using ionics built in `Events` functionality, supply  the tab index as parameter
2. In your underlying tabs, subscribe to the event using ionics built in `Events` and pick up the index, check if the index is the current tabs index

If you generate tabs dynamically, add `let i = index` in your ngFor and send to the tab using rootParams

**Comment by ihadeed** [comment]
@grimace 

If you want to detect that from inside the tab, you can listen to the `ViewController` events, or add the `ion` events. Examples:

```ts
ionViewWillEnter() {
  // run code before swiping into the tab
}

ionViewDidEnter() { }

ionViewWillLeave() { }

ionViewDidLeave() { }
```

**Comment by karlvd** [comment]
Great, thanks for clarifying! 
I closed my issue with the same question since this seems to be the preferred solution.

**Comment by grimace** [comment]
Perfect! I'm using ionViewWillEnter and it solved my problem.

**Comment by karlvd** [comment]
I did some tests with these triggers and it doesn´t seem to work correctly with Lazy loading.
`ionViewWillEnter()` and `ionViewDidEnter()` fire for the Tab entering into and neighboring tabs as well.

**Comment by ihadeed** [comment]
@karlvd do these events fire for the neighbouring tabs every time or just the first time swiping?

**Comment by karlvd** [comment]
It fires on neighboring Tabs on first load but not after that.

Assume you have a page with three tabs
Tab1 | Tab2 | Tab3

When entering the page with Tab1 visible the event will fire for Tab1 & Tab2
Swiping to Tab2 it fire for Tab2 & Tab3
Swiping back to Tab1 it will fire for Tab1 only
Swiping to Tab2 again it will fire for Tab2 only

So basically everything works correctly once the Tabs are loaded. The incorrect behavior is that it fires during lazy loading of neighboring tabs.

Hope it helps, let me know if you need any more info!

**Comment by ihadeed** [comment]
Ok I will look at this.

**Comment by karlvd** [comment]
@ihadeed Just want to check if this is in the roadmap to be fixed?
This prevent using supertabs in a scenario with Lazy loading + load content dynamically on tab select. I haven´t found any good workaround with events either since the non-loaded tabs doesn´t have an event listener unless they are a neighbour. The only way I found to have dynamically loaded content is to remove lazy loading for the tabs. I am looking now to remove lazy loading for my project but would rather not if this is coming in a release soon.

Appreciate the work you have done, supertabs is really great! I have tried to dig through the code to solve this but without any success, let me know if I can help in any other way!

**Comment by ihadeed** [comment]
@karlvd it is on the roadmap, but it's not going to be fixed any time soon. There are some changes that need to be done to the framework before being able to fix it on my end. 

What I can do now is add an option to only have 1 tab active at the same time (instead of initing the neighbouring tabs as well). This can probably help fix #104

**Comment by karlvd** [comment]
Thanks, understand that it´s dependent on changes in the framework so I appreciate the update the roadmap.

Yes I think that´s actually how I would like it to work. The function of pre-loading neighboring tabs work well and improves performance with static content but if you have dynamic content from a backend service it make much more sense to load the selected tab only. If you could add an option to only load the selected tab it would be great!

**Comment by karlvd** [comment]
For anyone else who need this functionality. A temporary solution which seems to work is to create a shared tabs service to keep track of the active index and keep it in a BehaviorSubject.

The service:
```
import { Injectable } from '@angular/core';
import { Observable, BehaviorSubject } from 'rxjs/Rx';
@Injectable()
export class TabsProvider {
  private tabIndex$ = new BehaviorSubject<number>(0);
  constructor() {
  }
  setTabIndex(index: number) {
    this.tabIndex$.next(index);
  }
  getTabIndex() {
    return this.tabIndex$.asObservable();
  }
}

```
In the view which contains the main `<super-tabs>` 
Set the index using the onTabselect() event

```
onTabSelect(ev: any) {      
    this.tabsProvider.setTabIndex(ev.index);
}

```
In each tab view (`<super-tab>`) subscribe to the Observable from the service and load data once it matches the current tab index.

```
ionViewDidLoad() {
    this.tabIndex = 2;
    this.tabsProvider.getTabIndex().subscribe((index) => {
      if (index == this.tabIndex) {
       loadData();
      }
    });
  }
```

With this solution it doesn´t matter if the view get loaded first (happens when the neighboring tab gets loaded while swiping) or if onTabSelect event fires before the view is loaded (happens when tapping a tab 2 tabs away from the current tab). If the value matches during view init it will load the data, if it´s not yet set by the event it will fire again when it changes.

Note that onTabsSelect() doesn´t fire on first load so you need to load data directly on the default tab when the tabs are created.

**Comment by kodeine** [comment]
Any updates on this?

**Comment by ihadeed** [comment]
Closing in favour of #61
