### ISSUE TITLE
Multiple tabs in a page.

### ISSUE THREAD

**Issue by kodeine** [zyra/ionic2-super-tabs#59]
Hello,
I have this one main tabs page and then on a different page i have segments which i want to use as sliding tabs as well. Is it possible to have 2 tabs, but then i would i control the swiping? Disable the main tabs swipe on that page? But is it even possible to have 2 tabs?
Can you share any example?

**Comment by ihadeed** [comment]
I haven't tried this since it's an ideal user experience design. Also, the material design guidelines says not to do such thing.

In theory, you should be able to do it by manually disabling the swiping on the main tabs element. You can do that by using the methods provided by SuperTabsController, and listening to the events emitted by the main tabs component.
