### ISSUE TITLE
rootParams is still a subscriber

### ISSUE THREAD

**Issue by lesrpo** [zyra/ionic2-super-tabs#62]
Hi, sorry if this is not a proper issue, but I cannot find the way to pass a variable through the rootParams.

My page is calling a service but the variable is still a subscriber when I get it in the 'Tab page'.

How can I send the data when is ready if the view will render first?

**Comment by ihadeed** [comment]
Can you share the view you're having trouble with?

**Comment by ihadeed** [comment]
Most likely the `SuperTabs` component is initialized before the value for `token` has been set. 

I suggest that you do one of the following:
- retrieve the token value in `Page1Page` instead of `MyPage` component
- retrieve the value in `MyPage` then send it to `Page1Page` via the Events provider (see Ionic Framework docs for info on this)

**Comment by lesrpo** [comment]
Thank you :)
