### ISSUE TITLE
Tabs below page header?

### ISSUE THREAD

**Issue by dayaki** [zyra/ionic2-super-tabs#72]
Could you please make it configurable to have the tabs below the header? Using css with `tabsPlacement="bottom"` is not having the desire effect. Or could you give pointer on how to achieve this?

**Comment by karlvd** [comment]
If you place the supertabs as the first tab under <ion-content> on a page it will appear under the header for that page.

You may want to remove the header from the pages that are tabs since it would just look strange with double headers. 

Hope it helps, if you still struggle, post a few screenshots and explain how it looks now and how you want it to look.

**Comment by dayaki** [comment]
@karlvd I think you got me wrong.

**The first image below is what am trying to achieve with super-tabs**
![scroll1](https://user-images.githubusercontent.com/815619/26923269-80513b70-4c39-11e7-8a83-c8c3ef6e6c4c.png)
<br><br>

**But this is what am getting.**
![scroll2](https://user-images.githubusercontent.com/815619/26923272-867267a4-4c39-11e7-9181-830daa6d9cab.png)

**Comment by ihadeed** [comment]
You can add the `no-shadow` attribute to your `super-tabs` component.

**Comment by dayaki** [comment]
@ihadeed the problem is not the shadow. its the placement of the tabs, **I want the tabs to be below the page header**. Like this

![scroll1](https://user-images.githubusercontent.com/815619/26924407-9f6a47aa-4c3d-11e7-872e-fd1ef44cf13a.png)

**Comment by karlvd** [comment]
I think this is what you need to do
1. Add a <ion-header> to the page containing the super-tabs
2. Remove the <ion-header> from the pages displayed by each tab, your "top stories", "headlines" and "dailies" pages

**Comment by dayaki** [comment]
@karlvd Can you please explain better?

1. I should add what?
2. I should remove what?

**Comment by karlvd** [comment]
Forgot to mark the code, see the above comment again, it´s updated

**Comment by dayaki** [comment]
@karlvd thanks its working BUT it raises another question. @ihadeed is there anything like `tabsHideOnSubPages` ???

**Comment by ihadeed** [comment]
@dayaki 

Oh, I see. There is no option to have the tabs under the sub-page header. This module was designed according to the material design spec. I looked at different apps using swipeable tabs and I saw that they use a common header for all their tabs. These tabs are not meant for main navigation, they're intended for things like categories. 

For example, you would have a "Shop" page. Then you use these tabs to have different categories: "Men, Women, Kids, Electronics ...etc". Or a "Profile" page with "Feed, Followings, Followers .. etc".

It is possible to have different headers for each tab, but that would require lots of work to get it perfect. Ideally the header shouldn't slide, it should just fade in and out, or change instantly. Otherwise, it would just look like a very long header bar. This feature is not a priority at the moment, and I can't give you any estimate on when it will be added. 

To answer you second question, there isn't anything like `tabsHideOnSubPages`. If you want to achieve such functionality, you can follow this example: https://github.com/zyra/ionic2-super-tabs-example/blob/master/src/pages/page1/page1.ts#L22

`rootNavCtrl` is automatically added to the `NavParams` of all sub-tabs. It references to the `NavController` of the page containing the `super-tabs` component. This allows you to push pages from the root page rather than the inner one.

**Comment by dayaki** [comment]
@ihadeed `rootNavCtrl` seems to be passed only to the first sub-tab, other sub-tabs doesnt have `rootNavCtrl` passed via `NavParams`

**Comment by philipgriffin** [comment]
@dayaki @karlvd 
If either of you have a solution to produce the aforementioned picture it would be great to hear.

I have attempted this (see code below) as suggested.

```
<ion-header no-border>
  <ion-navbar color="primary">
    <ion-buttons right>
      <button ion-button menuToggle>
        <ion-icon name="menu"></ion-icon>
      </button>
    </ion-buttons>
    <ion-title></ion-title>
  </ion-navbar>
</ion-header>

  <super-tabs toolbarColor="dark" indicatorColor="dark" toolbarBackground="primary">
    <super-tab [root]="tab1Root" title="NEARBY"></super-tab>
    <super-tab [root]="tab2Root" title="NEW"></super-tab>
    <super-tab [root]="tab3Root" title="SAVED"></super-tab>
    <super-tab [root]="tab3Root" title="EVENTS"></super-tab>
  </super-tabs>
```

The issue with this however is that the `navbar `overlaps the `supertabs`. Likely because the `supertabs `have 100% height by default. Changing this using something like 
```
super-tabs  {
height:  calc(100% - 56px) !important;
top: 56px !important;
}
```
Would be useful but the `top: 56px !important;` rule is ignored so it results in the `navbar `overlapping the tabs and the bottom of the tabs being cut short.

**Comment by philipgriffin** [comment]
I solved my issue, I needed to add `ion-content` tags to my tabs.html file like so...

```
<ion-header no-border>
  <ion-navbar color="primary">
    <ion-buttons right>
      <button ion-button menuToggle>
        <ion-icon name="menu"></ion-icon>
      </button>
    </ion-buttons>
    <ion-title></ion-title>
  </ion-navbar>
</ion-header>
<ion-content>
<super-tabs toolbarColor="dark" indicatorColor="dark" toolbarBackground="primary">
  <super-tab [root]="tab1Root" title="NEARBY"></super-tab>
  <super-tab [root]="tab2Root" title="NEW"></super-tab>
  <super-tab [root]="tab3Root" title="SAVED"></super-tab>
  <super-tab [root]="tab3Root" title="EVENTS"></super-tab>
</super-tabs>
</ion-content>
```

**Comment by anandraj9497** [comment]
Hi I am facing the same issue.

**Comment by joshuaalvaro** [comment]
Hi, the solution is for the ion-bar to be on the same page as the header. What about if my ion-tab is on a different page? If I add slot="start", then my tab will be above everything else in the page, but I can't place it between the header and the content. Can anyone tell me how to do it?
